// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm0KQzfkUdnR0gRYibL4OBRPGu9eS7ewk',
    appId: '1:227909909647:web:07c269367483ed6dbe04fa',
    messagingSenderId: '227909909647',
    projectId: 'evyree-d924b',
    authDomain: 'evyree-d924b.firebaseapp.com',
    databaseURL: 'https://evyree-d924b-default-rtdb.firebaseio.com',
    storageBucket: 'evyree-d924b.appspot.com',
    measurementId: 'G-XQBD7KD4KT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBng9-mdmVC9iE3ceHYH-JdWMkQkCUrzVk',
    appId: '1:227909909647:android:86de7c701f48bbb9be04fa',
    messagingSenderId: '227909909647',
    projectId: 'evyree-d924b',
    databaseURL: 'https://evyree-d924b-default-rtdb.firebaseio.com',
    storageBucket: 'evyree-d924b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA5SMM-OUATgkQp0a-CObFAy6CQwoCwKs',
    appId: '1:227909909647:ios:868016ee06efb994be04fa',
    messagingSenderId: '227909909647',
    projectId: 'evyree-d924b',
    databaseURL: 'https://evyree-d924b-default-rtdb.firebaseio.com',
    storageBucket: 'evyree-d924b.appspot.com',
    iosBundleId: 'com.example.circlesYesNo',
  );
}
